FROM centos:7
RUN yum update -y
RUN yum install gcc -y
RUN yum install gdb -y
RUN yum install python2 -y
RUN yum install python3 -y
RUN curl -sL https://rpm.nodesource.com/setup_8.x | bash -
RUN yum install nodejs -y